# Testing AirGravQC - Example Data

Mark Dransfield

In [1]:
import datetime
print(datetime.datetime.now())

2023-12-01 15:22:29.687423

## Introduction

## Import and Summarise

#### Import required modules, and set filenames for data and plan.

> First import external packages. *Some of these are probably not needed here.*

In [2]:
# import sys
import importlib as im

%matplotlib widget

from pathlib import Path

> Set the paths for the `AirGravQC` software and import. (One day this will require fewer steps.)

In [3]:
# Choose `local_docs` to suit you.
# local_docs = "/Users/markdransfield/Library/Mobile Documents/com~apple~CloudDocs/"
local_docs = "/Users/markdransfield/"
# local_docs = "/Users/markdransfield/Library/Mobile Documents/com~apple~CloudDocs/"
# src_path = local_docs + "Documents/GitHub/AirGravQC/AirGravQC"
# sys.path.insert(0, src_path)

import AirGravQC as qc

# import pointfiles as mhd
# import qualityAnalysis as qc
# import whizzPlot as wp
# import gridfiles as grd

> Set the paths for the data. Usually the data would be from only one project but here we are including a variety of exemplars.

> Modify to suit your data.

In [4]:
data_root = local_docs + "Documents/GitHub/AirGravQC/examples/Airmag_GDF/"

muppetGDF_file = Path(data_root + r'Example_AeroMag_MuppetTown_2009.dfn')
muppetHDF_file = muppetGDF_file.with_suffix('.hdf5')

In [5]:
import aseg_gdf2 as aseg

In [73]:
gdf = aseg.read(muppetGDF_file, method='fixed-widths')#, engine='pandas')

In [77]:
field_nmes = gdf.field_names()

['BGS_JOB',
 'LINE',
 'FLIGHT',
 'DATE',
 'FIDUCIAL',
 'EAST_MGA',
 'NORTH_MGA',
 'GDA94LAT',
 'GDA94LON',
 'MAGUNCMP',
 'MAGCOMP',
 'DIURNAL',
 'IGRF',
 'MAG_LEV',
 'RAD_ALT',
 'GPS_HT',
 'DEM']

In [78]:
df = gdf.df()

In [79]:
gby = df.groupby(df.LINE)

In [80]:
result = gby.count()

In [88]:
result

,BGS_JOB,FLIGHT,DATE,FIDUCIAL,EAST_MGA,NORTH_MGA,GDA94LAT,GDA94LON,MAGUNCMP,MAGCOMP,DIURNAL,IGRF,MAG_LEV,RAD_ALT,GPS_HT,DEM
LINE,,,,,,,,,,,,,,,,
10010.0,1050,1050,1050,1050,1050,1050,1050,1050,1050,1050,1050,1050,1050,1050,1050,1050

In [106]:
result.BGS_JOB.values[0]

1050

In [95]:
i = 0
result.axes[0][i]

10010.0

In [123]:
gdf = aseg.read(muppetGDF_file, method='fixed-widths')#, engine='pandas')
df = gdf.df()
gby = df.groupby(df['LINE'])
result = gby.count()
field_names = gdf.field_names()
for i in range(0, 1):
    print(result.axes[0][i])
    for j in range(0, len(field_names)-1):
        print(result[field_names[0]].values[0])#result.axes[1][j])

10010.0
1050
1050
1050
1050
1050
1050
1050
1050
1050
1050
1050
1050
1050
1050
1050
1050

In [126]:
result[field_names[3]].values[0]

1050

In [128]:
field_names[1]

'LINE'

In [74]:
aa = gdf.record_types.df()

/Users/markdransfield/opt/miniconda3/envs/whizz/lib/python3.10/site-packages/aseg_gdf2/gdf2.py:45: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  df = json_normalize(v, ["fields"])
/Users/markdransfield/opt/miniconda3/envs/whizz/lib/python3.10/site-packages/aseg_gdf2/gdf2.py:45: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  df = json_normalize(v, ["fields"])

In [75]:
print(gdf.record_types.df().to_string(index=False))

record_type      name format    unit       null      long_name comment  cols  width
       COMM        RT     A4               None                            1      4
       COMM  COMMENTS    A80               None                            1     80
              BGS_JOB     A5               None                            1      5
                 LINE     A8               None                            1      8
               FLIGHT     I4               None                            1      4
                 DATE     A8               None                            1      8
             FIDUCIAL  f12.1          -999999.0       fiducial             1     12
             EAST_MGA  f11.2  METRES  -99999.00        Easting             1     11
            NORTH_MGA  f11.2  METRES  -99999.00       Northing             1     11
             GDA94LAT  f12.7 degrees -99.000000      wgs84_lat             1     12
             GDA94LON  f13.7 degrees -999.00000     wgs84_long             1     13
             MAGUNCMP  f10.3      nT  -9999.000        raw_mag             1     10
              MAGCOMP  f10.3      nT  -9999.000     mag_gammas             1     10
              DIURNAL  f10.3      nT  -9999.000 diurnal_gammas             1     10
                 IGRF  f10.3      nT  -9999.000    igrf_gammas             1     10
              MAG_LEV  f10.3      nT  -9999.000      mag_level             1     10
              RAD_ALT   f8.2  METRES    -999.00        rad_alt             1      8
               GPS_HT   f8.2  METRES    -999.00     gps_height             1      8
                  DEM   f8.2  METRES    -999.00            dtm             1      8

/Users/markdransfield/opt/miniconda3/envs/whizz/lib/python3.10/site-packages/aseg_gdf2/gdf2.py:45: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  df = json_normalize(v, ["fields"])
/Users/markdransfield/opt/miniconda3/envs/whizz/lib/python3.10/site-packages/aseg_gdf2/gdf2.py:45: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  df = json_normalize(v, ["fields"])

In [76]:
print(gdf.record_types.df().to_string(index=False), '\n')
print(gdf.df().head(1))

record_type      name format    unit       null      long_name comment  cols  width
       COMM        RT     A4               None                            1      4
       COMM  COMMENTS    A80               None                            1     80
              BGS_JOB     A5               None                            1      5
                 LINE     A8               None                            1      8
               FLIGHT     I4               None                            1      4
                 DATE     A8               None                            1      8
             FIDUCIAL  f12.1          -999999.0       fiducial             1     12
             EAST_MGA  f11.2  METRES  -99999.00        Easting             1     11
            NORTH_MGA  f11.2  METRES  -99999.00       Northing             1     11
             GDA94LAT  f12.7 degrees -99.000000      wgs84_lat             1     12
             GDA94LON  f13.7 degrees -999.00000     wgs84_long             1     13
             MAGUNCMP  f10.3      nT  -9999.000        raw_mag             1     10
              MAGCOMP  f10.3      nT  -9999.000     mag_gammas             1     10
              DIURNAL  f10.3      nT  -9999.000 diurnal_gammas             1     10
                 IGRF  f10.3      nT  -9999.000    igrf_gammas             1     10
              MAG_LEV  f10.3      nT  -9999.000      mag_level             1     10
              RAD_ALT   f8.2  METRES    -999.00        rad_alt             1      8
               GPS_HT   f8.2  METRES    -999.00     gps_height             1      8
                  DEM   f8.2  METRES    -999.00            dtm             1      8

   BGS_JOB     LINE  FLIGHT        DATE  FIDUCIAL   EAST_MGA  NORTH_MGA   GDA94LAT    GDA94LON   MAGUNCMP    MAGCOMP  \
0      954  10010.0     1.0  20091202.0    8085.5  540024.19  6201024.0 -34.331295  147.435104  58267.879  58268.254

     DIURNAL       IGRF  MAG_LEV  RAD_ALT  GPS_HT     DEM
0  57929.934  57944.402  334.758    37.27  299.82  265.71

/Users/markdransfield/opt/miniconda3/envs/whizz/lib/python3.10/site-packages/aseg_gdf2/gdf2.py:45: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  df = json_normalize(v, ["fields"])
/Users/markdransfield/opt/miniconda3/envs/whizz/lib/python3.10/site-packages/aseg_gdf2/gdf2.py:45: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  df = json_normalize(v, ["fields"])

In [44]:
df = gdf.df(assume_missing=True)
df

Dask DataFrame Structure:
               BGS_JOB     LINE   FLIGHT     DATE FIDUCIAL EAST_MGA NORTH_MGA GDA94LAT GDA94LON MAGUNCMP  MAGCOMP  DIURNAL     IGRF  MAG_LEV  RAD_ALT   GPS_HT      DEM
npartitions=1
               float64  float64  float64  float64  float64  float64   float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64
                   ...      ...      ...      ...      ...      ...       ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...
Dask Name: read-csv, 1 tasks

In [45]:
flights = df['LINE'].unique()

In [46]:
flights[0].compute()

0    10010.0
Name: LINE, dtype: float64

In [32]:
gdf.field_names()

['BGS_JOB',
 'LINE',
 'FLIGHT',
 'DATE',
 'FIDUCIAL',
 'EAST_MGA',
 'NORTH_MGA',
 'GDA94LAT',
 'GDA94LON',
 'MAGUNCMP',
 'MAGCOMP',
 'DIURNAL',
 'IGRF',
 'MAG_LEV',
 'RAD_ALT',
 'GPS_HT',
 'DEM']

In [51]:
print(gdf.df().head(1))

   BGS_JOB     LINE  FLIGHT        DATE  FIDUCIAL   EAST_MGA  NORTH_MGA  \
0      954  10010.0     1.0  20091202.0    8085.5  540024.19  6201024.0

    GDA94LAT    GDA94LON   MAGUNCMP    MAGCOMP    DIURNAL       IGRF  MAG_LEV  \
0 -34.331295  147.435104  58267.879  58268.254  57929.934  57944.402  334.758

   RAD_ALT  GPS_HT     DEM
0    37.27  299.82  265.71

### Muppet Project Measured Data

#### Convert measured XYZ data to geoWhizz, and set metadata

> The next step is essential. We need the data in HDF5 geoWhizz format because all the QC functions expect that format. (More on the geoWhizz format in the `AirGravQC` documentation.)

> Geosoft XYZ files generally have only the channel names, and no other metadata. We need the attributes of the data at project level, at line number level, and at data channel level.

In [5]:
# import AirGravQC
# # AirGravQC.aseg_gdf2.gdf2.read(str(muppetGDF_file), method='fixed-widths')
# aa = AirGravQC.aseg_gdf2.read(str(muppetGDF_file), method='fixed-widths')

In [6]:
qc.asegToHDF(muppetGDF_file)

2 Indices - line 1, flight 2, date 3, zone -1
1 channels out:
['BGS_JOB', 'LINE', 'FLIGHT', 'DATE', 'FIDUCIAL', 'EAST_MGA', 'GDA94LAT', 'GDA94LON', 'MAGUNCMP', 'MAGCOMP', 'DIURNAL', 'IGRF', 'MAG_LEV', 'RAD_ALT', 'GPS_HT', 'DEM']

Getting line numbers and lengths ...

AttributeError: 'GDF2' object has no attribute 'df_chunked'

> Now we demonstrate the use of `updateProject()` to add additional project attributes.

> It also shows the use of `updateCoordFrame()` which keeps track of the coordinate definition and the names of the channels that contain position and time. Many QC routines use position and time, so it saves effort later to have this information in the geoWhizz group attributes.

> Field data are commonly delivered to WGS84, projected to UTM, because that is what GNSS delivers. Transformation to the desired datum happens at the end of the project for the final data.

In [ ]:
block_name = 'A line from Muppet Aeromag Data'
qc.updateProject(muppetHDF_file, acquirer='Xcalibur Multiphysics', blockID=block_name)
qc.updateCoordFrame(muppetHDF_file, lat='LATITUDE', lon='LONGITUDE', x='EASTING', y='NORTHING', time='Time_1980', alt='HEIGHT')
qc.updateCoordFrame(muppetHDF_file, geoDatum='WGS84', htDatum='WGS84', projection='UTM', utmz='54')

> The line attributes represent a challenge. Line numbers are usually coded to contain a number of impoprtant attributes: whether the line is a traverse, control, repeat or test line; which segment of a number of segments needed to complete the line, and whether it is a re-flight; and what is the line number of the corresponding planned line number. Each supplier uses a different coding system, and sometimes they will use different codings for different projects (or, worst of all (but vary rare), between staff processing the data on the same project!).

> AirGravQC knows only 3 of these systems so far and this will need expanding. So beware!

In [ ]:
qc.updateLineAttributes(canobieHDF_file, line_type='Xcal_can')

> The acquirers of the data supplied a separate text file `Channel Descriptions.txt` with the requisite channel attributes metadata which then had to be entered manually via this series of commands to store it in the geoWhizz file created by `xyzToHDF()`. There is some drudgery involved here which you will have to do for your project.

> I did not enter in the supplied descriptions for the channel attributes so all that is happening here is storing the units for each channel. Units are used in some QC checking. *Could we automate this process by reading channel description files?*

In [ ]:
qc.updateChannelAttributes(canobieHDF_file, 'ANE_TC_2p67', units='eotvos')
qc.updateChannelAttributes(canobieHDF_file, 'AUV_TC_2p67', units='eotvos')
qc.updateChannelAttributes(canobieHDF_file, 'Bearing', units='degrees')
qc.updateChannelAttributes(canobieHDF_file, 'BNE_TC_2p67', units='eotvos')
qc.updateChannelAttributes(canobieHDF_file, 'BUV_TC_2p67', units='eotvos')
qc.updateChannelAttributes(canobieHDF_file, 'CLEARANCE', units='metre')
qc.updateChannelAttributes(canobieHDF_file, 'Date')
qc.updateChannelAttributes(canobieHDF_file, 'DTM', units='metre')
qc.updateChannelAttributes(canobieHDF_file, 'EASTING', units='metre')
qc.updateChannelAttributes(canobieHDF_file, 'FIDUCIAL')
qc.updateChannelAttributes(canobieHDF_file, 'FLIGHT')
qc.updateChannelAttributes(canobieHDF_file, 'gD_Fourier_2p67', units='µm/s/s')
qc.updateChannelAttributes(canobieHDF_file, 'GDD_Fourier_2p67', units='eotvos')
qc.updateChannelAttributes(canobieHDF_file, 'GNE_Fourier_2p67', units='eotvos')
qc.updateChannelAttributes(canobieHDF_file, 'GUV_Fourier_2p67', units='eotvos')
qc.updateChannelAttributes(canobieHDF_file, 'HDOP')
qc.updateChannelAttributes(canobieHDF_file, 'HEIGHT', units='metre')
qc.updateChannelAttributes(canobieHDF_file, 'JOB_ID')
qc.updateChannelAttributes(canobieHDF_file, 'LATITUDE', units='degree')
qc.updateChannelAttributes(canobieHDF_file, 'LINE')
qc.updateChannelAttributes(canobieHDF_file, 'LONGITUDE', units='degree')
qc.updateChannelAttributes(canobieHDF_file, 'Noise_NE', units='eotvos')
qc.updateChannelAttributes(canobieHDF_file, 'Noise_UV', units='eotvos')
qc.updateChannelAttributes(canobieHDF_file, 'NORTHING', units='metre')
qc.updateChannelAttributes(canobieHDF_file, 'NumSats')
qc.updateChannelAttributes(canobieHDF_file, 'PDOP')
qc.updateChannelAttributes(canobieHDF_file, 'T_DD', units='eotvos')
qc.updateChannelAttributes(canobieHDF_file, 'T_NE', units='eotvos')
qc.updateChannelAttributes(canobieHDF_file, 'T_UV', units='µm/s/s')
qc.updateChannelAttributes(canobieHDF_file, 'Time_1980', units='seconds')
qc.updateChannelAttributes(canobieHDF_file, 'Time_Day', units='seconds')
qc.updateChannelAttributes(canobieHDF_file, 'TURBULENCE', units='m/s/s')
qc.updateChannelAttributes(canobieHDF_file, 'VDOP')

#### Summary report of measured data

> Summary report of contents of data file. The `reportWhizz()` code can list attributes of a line via the `line=...` keyword, or a channel via the `channel=...` keyword.

In [ ]:
qc.reportWhizz(canobieHDF_file, channel='ANE_TC_2p67')

In [ ]:
qc.reportFlights(canobieHDF_file, detailed=True)

> Sample times should be constant. Here we have one at 0.126 which ought to be checked. Sample distances vary with aircraft ground speed.

In [ ]:
qc.reportSampling(canobieHDF_file)

### Canobie Plan Data

#### Convert plan XYZ data to geoWhizz, and set metadata

In this example, the plan data file only has the (x,y) locations of the start and end of each line and we have no planned heights. The process is the same as for the acquired survey data `XYZ` file above.

In [ ]:
qc.xyzToHDF(Path(canobieXYZ_plan), projectName='Canobie')
block_name = 'Survey Plan'
qc.updateProject(canobieHDF_plan, acquirer='Xcalibur Multiphysics', blockID=block_name)

In [ ]:
qc.updateCoordFrame(canobieHDF_plan, x='EASTING', y='NORTHING')
qc.updateCoordFrame(canobieHDF_plan, geoDatum='WGS84', projection='UTM', utmz='54')
qc.updateLineAttributes(canobieHDF_plan, line_type='Xcal_can')

In [ ]:
qc.updateChannelAttributes(canobieHDF_plan, 'EASTING', units='m')
qc.updateChannelAttributes(canobieHDF_plan, 'NORTHING', units='m')

#### Summary report of plan data

In [ ]:
qc.reportWhizz(canobieHDF_plan)

#### Map showing flown lines against plan.

> This provides a visual check that the lines are in about the right location and shows the amount of the survey flown so far.

In [ ]:
wp.linesMap([canobieHDF_file], whizzPlanFile=canobieHDF_plan)

### EastVic Project Measured Data

In [ ]:
qc.xyzToHDF(Path(EastVicXYZ_file), projectName='EastVic')

In [ ]:
block_name = 'EastVic Field Data'
qc.updateProject(EastVicHDF_file, acquirer='Sander Geophysics', blockID=block_name)
qc.updateCoordFrame(EastVicHDF_file, lat='LAT', lon='LONG', x='MGA_X', y='MGA_Y', time='FTIME', alt='MGA_Z')
qc.updateCoordFrame(EastVicHDF_file, geoDatum='GDA2020', htDatum='GRS80', projection='MGA', utmz='55')

In [ ]:
qc.updateLineAttributes(EastVicHDF_file, line_type='SGL_GA', flight_chan='FLIGHT', date_chan="DOY")

In [ ]:
qc.updateChannelAttributes(EastVicHDF_file, 'FTIME', units='s')
qc.updateChannelAttributes(EastVicHDF_file, 'MGA_X', units='m')
qc.updateChannelAttributes(EastVicHDF_file, 'MGA_Y', units='m')
qc.updateChannelAttributes(EastVicHDF_file, 'MGA_Z', units='m')
qc.updateChannelAttributes(EastVicHDF_file, 'MSL_Z', units='m')
qc.updateChannelAttributes(EastVicHDF_file, 'LAT', units='degree')
qc.updateChannelAttributes(EastVicHDF_file, 'LONG', units='degree')
qc.updateChannelAttributes(EastVicHDF_file, 'DEM', units='m')
qc.updateChannelAttributes(EastVicHDF_file, 'RALT', units='m')
qc.updateChannelAttributes(EastVicHDF_file, 'LALT', units='m')
qc.updateChannelAttributes(EastVicHDF_file, 'FX', units='mGal')
qc.updateChannelAttributes(EastVicHDF_file, 'FY', units='mGal')
qc.updateChannelAttributes(EastVicHDF_file, 'FZ', units='mGal')
qc.updateChannelAttributes(EastVicHDF_file, 'V_EAST', units='m/s')
qc.updateChannelAttributes(EastVicHDF_file, 'V_NORTH', units='m/s')
qc.updateChannelAttributes(EastVicHDF_file, 'EOTCOR', units='mGal')
qc.updateChannelAttributes(EastVicHDF_file, 'LATCOR', units='mGal')
qc.updateChannelAttributes(EastVicHDF_file, 'STATCOR', units='mGal')
qc.updateChannelAttributes(EastVicHDF_file, 'ATMCOR', units='mGal')
qc.updateChannelAttributes(EastVicHDF_file, 'FACOR_GRS80', units='mGal')
qc.updateChannelAttributes(EastVicHDF_file, 'FACOR_GEOID', units='mGal')
qc.updateChannelAttributes(EastVicHDF_file, 'TACOR', units='mGal')
qc.updateChannelAttributes(EastVicHDF_file, 'FA56s_GRS80', units='mGal')
qc.updateChannelAttributes(EastVicHDF_file, 'FA56s_GEOID', units='mGal')
qc.updateChannelAttributes(EastVicHDF_file, 'FA100s_GRS80', units='mGal')
qc.updateChannelAttributes(EastVicHDF_file, 'FA100s_GEOID', units='mGal')
qc.updateChannelAttributes(EastVicHDF_file, 'B56s_267_GRS80', units='mGal')
qc.updateChannelAttributes(EastVicHDF_file, 'B56s_267_GEOID', units='mGal')
qc.updateChannelAttributes(EastVicHDF_file, 'B100s_267_GRS80', units='mGal')
qc.updateChannelAttributes(EastVicHDF_file, 'B100s_267_GEOID', units='mGal')

In [ ]:
qc.reportWhizz(EastVicHDF_file, line='2341.5', channel='ATMCOR')

In [ ]:
qc.reportFlights(EastVicHDF_file, detailed=True)

In [ ]:
qc.reportSampling(EastVicHDF_file)

### EastVic Repeat Line Data

In [ ]:
qc.xyzToHDF(Path(EastVicRepXYZ_file), projectName='EastVic')

In [ ]:
block_name = 'EastVic Repeat Line Data'
qc.updateProject(EastVicRepHDF_file, acquirer='Sander Geophysics', blockID=block_name)
qc.updateCoordFrame(EastVicRepHDF_file, lat='LAT', lon='LONG', x='MGA-X', y='MGA-Y', time='FTIME', alt='MGA-Z')
qc.updateCoordFrame(EastVicRepHDF_file, geoDatum='GDA2020', htDatum='GRS80', projection='MGA', utmz='55')

In [ ]:
qc.updateLineAttributes(EastVicRepHDF_file, line_type='SGL_GA')

In [ ]:
qc.updateChannelAttributes(EastVicRepHDF_file, 'FTIME', units='s')
qc.updateChannelAttributes(EastVicRepHDF_file, 'MGA-X', units='m')
qc.updateChannelAttributes(EastVicRepHDF_file, 'MGA-Y', units='m')
qc.updateChannelAttributes(EastVicRepHDF_file, 'MGA-Z', units='m')
qc.updateChannelAttributes(EastVicRepHDF_file, 'MSL-Z', units='m')
qc.updateChannelAttributes(EastVicRepHDF_file, 'LAT', units='degree')
qc.updateChannelAttributes(EastVicRepHDF_file, 'LONG', units='degree')
qc.updateChannelAttributes(EastVicRepHDF_file, 'DEM', units='m')
qc.updateChannelAttributes(EastVicRepHDF_file, 'RALT', units='m')
qc.updateChannelAttributes(EastVicRepHDF_file, 'LALT', units='m')
qc.updateChannelAttributes(EastVicRepHDF_file, 'FX', units='mGal')
qc.updateChannelAttributes(EastVicRepHDF_file, 'FY', units='mGal')
qc.updateChannelAttributes(EastVicRepHDF_file, 'FZ', units='mGal')
qc.updateChannelAttributes(EastVicRepHDF_file, 'V_EAST', units='m/s')
qc.updateChannelAttributes(EastVicRepHDF_file, 'V_NORTH', units='m/s')
qc.updateChannelAttributes(EastVicRepHDF_file, 'EOTCOR', units='mGal')
qc.updateChannelAttributes(EastVicRepHDF_file, 'LATCOR', units='mGal')
qc.updateChannelAttributes(EastVicRepHDF_file, 'STATCOR', units='mGal')
qc.updateChannelAttributes(EastVicRepHDF_file, 'ATMCOR', units='mGal')
qc.updateChannelAttributes(EastVicRepHDF_file, 'FACOR_GRS80', units='mGal')
qc.updateChannelAttributes(EastVicRepHDF_file, 'FACOR_GEOID', units='mGal')
qc.updateChannelAttributes(EastVicRepHDF_file, 'TACOR', units='mGal')
qc.updateChannelAttributes(EastVicRepHDF_file, 'FA56s_GRS80', units='mGal')
qc.updateChannelAttributes(EastVicRepHDF_file, 'FA56s_GEOID', units='mGal')
qc.updateChannelAttributes(EastVicRepHDF_file, 'FA100s_GRS80', units='mGal')
qc.updateChannelAttributes(EastVicRepHDF_file, 'FA100s_GEOID', units='mGal')
qc.updateChannelAttributes(EastVicRepHDF_file, 'B56s-267_GRS80', units='mGal')
qc.updateChannelAttributes(EastVicRepHDF_file, 'B56s-267_GEOID', units='mGal')
qc.updateChannelAttributes(EastVicRepHDF_file, 'B100s-267_GRS80', units='mGal')
qc.updateChannelAttributes(EastVicRepHDF_file, 'B100s-267_GEOID', units='mGal')

In [ ]:
qc.reportWhizz(EastVicRepHDF_file)

In [ ]:
qc.reportFlights(EastVicRepHDF_file, detailed=False)

In [ ]:
qc.reportSampling(EastVicRepHDF_file)

### EastVic Test Line Data

In [ ]:
qc.xyzToHDF(Path(EastVicTestXYZ_file), projectName='EastVic')

<div class="alert alert-block alert-danger">
What is happening? ASEG_To_HDF should import this info automatically
from DFN and MET file.
<div>

In [ ]:
block_name = 'EastVic Test Line Data'
qc.updateProject(EastVicTestHDF_file, acquirer='Sander Geophysics', blockID=block_name)
qc.updateCoordFrame(EastVicTestHDF_file, lat='LAT', lon='LONG', x='MGA-X', y='MGA-Y', time='FTIME', alt='MGA-Z')
qc.updateCoordFrame(EastVicTestHDF_file, geoDatum='GDA2020', htDatum='GRS80', projection='MGA', utmz='55')

In [ ]:
qc.updateLineAttributes(EastVicTestHDF_file, line_type='SGL_GA')

In [ ]:
qc.updateChannelAttributes(EastVicTestHDF_file, 'FTIME', units='s')
qc.updateChannelAttributes(EastVicTestHDF_file, 'MGA-X', units='m')
qc.updateChannelAttributes(EastVicTestHDF_file, 'MGA-Y', units='m')
qc.updateChannelAttributes(EastVicTestHDF_file, 'MGA-Z', units='m')
qc.updateChannelAttributes(EastVicTestHDF_file, 'MSL-Z', units='m')
qc.updateChannelAttributes(EastVicTestHDF_file, 'LAT', units='degree')
qc.updateChannelAttributes(EastVicTestHDF_file, 'LONG', units='degree')
qc.updateChannelAttributes(EastVicTestHDF_file, 'DEM', units='m')
qc.updateChannelAttributes(EastVicTestHDF_file, 'RALT', units='m')
qc.updateChannelAttributes(EastVicTestHDF_file, 'LALT', units='m')
qc.updateChannelAttributes(EastVicTestHDF_file, 'FX', units='mGal')
qc.updateChannelAttributes(EastVicTestHDF_file, 'FY', units='mGal')
qc.updateChannelAttributes(EastVicTestHDF_file, 'FZ', units='mGal')
qc.updateChannelAttributes(EastVicTestHDF_file, 'V_EAST', units='m/s')
qc.updateChannelAttributes(EastVicTestHDF_file, 'V_NORTH', units='m/s')
qc.updateChannelAttributes(EastVicTestHDF_file, 'EOTCOR', units='mGal')
qc.updateChannelAttributes(EastVicTestHDF_file, 'LATCOR', units='mGal')
qc.updateChannelAttributes(EastVicTestHDF_file, 'STATCOR', units='mGal')
qc.updateChannelAttributes(EastVicTestHDF_file, 'ATMCOR', units='mGal')
qc.updateChannelAttributes(EastVicTestHDF_file, 'FACOR_GRS80', units='mGal')
qc.updateChannelAttributes(EastVicTestHDF_file, 'FACOR_GEOID', units='mGal')
qc.updateChannelAttributes(EastVicTestHDF_file, 'TACOR', units='mGal')
qc.updateChannelAttributes(EastVicTestHDF_file, 'FA56s_GRS80', units='mGal')
qc.updateChannelAttributes(EastVicTestHDF_file, 'FA56s_GEOID', units='mGal')
qc.updateChannelAttributes(EastVicTestHDF_file, 'FA100s_GRS80', units='mGal')
qc.updateChannelAttributes(EastVicTestHDF_file, 'FA100s_GEOID', units='mGal')
qc.updateChannelAttributes(EastVicTestHDF_file, 'B56s-267_GRS80', units='mGal')
qc.updateChannelAttributes(EastVicTestHDF_file, 'B56s-267_GEOID', units='mGal')
qc.updateChannelAttributes(EastVicTestHDF_file, 'B100s-267_GRS80', units='mGal')
qc.updateChannelAttributes(EastVicTestHDF_file, 'B100s-267_GEOID', units='mGal')

In [ ]:
qc.reportWhizz(EastVicTestHDF_file)

In [ ]:
qc.reportFlights(EastVicTestHDF_file, detailed=False)

In [ ]:
qc.reportSampling(EastVicTestHDF_file)

### EastVic Plan Data

In [ ]:
qc.xyzToHDF(Path(EastVicXYZ_plan), projectName='EastVic')
block_name = 'Survey Plan'
qc.updateProject(EastVicHDF_plan, acquirer='Sander Geophysics', blockID=block_name)

In [ ]:
qc.updateCoordFrame(EastVicHDF_plan, x='W84_UTM_55S_X_m', y='W84_UTM_55S_Y_m', alt='Drape_m')
qc.updateCoordFrame(EastVicHDF_plan, geoDatum='WGS84', projection='UTM', utmz='55')
qc.updateLineAttributes(EastVicHDF_plan, line_type='SGL_GA')

In [ ]:
qc.updateChannelAttributes(EastVicHDF_plan, 'W84_UTM_55S_X_m', units='m')
qc.updateChannelAttributes(EastVicHDF_plan, 'W84_UTM_55S_Y_m', units='m')
qc.updateChannelAttributes(EastVicHDF_plan, 'Drape_m', units='m')

In [ ]:
qc.reportWhizz(EastVicHDF_plan)

In [ ]:
wp.linesMap([EastVicHDF_file], whizzPlanFile=EastVicHDF_plan)

### Blackstump Project Measured Data

In [ ]:
qc.xyzToHDF(Path(stumpXYZ_file), projectName='Blackstump')

In [ ]:
block_name = 'Prelim Blackstump Data'
qc.updateProject(stumpHDF_file, acquirer='Welcome Swallow', blockID=block_name)
qc.updateCoordFrame(stumpHDF_file, lat='lat', lon='lon', x='X_gda94', y='Y_gda94', time='time', alt='altitude')
qc.updateCoordFrame(stumpHDF_file, geoDatum='GDA94', htDatum='GDA94', projection='MGA', utmz='50')

In [ ]:
qc.updateChannelAttributes(stumpHDF_file, 'altitude', units='m')
qc.updateChannelAttributes(stumpHDF_file, 'altitude_ftp', units='m')
qc.updateChannelAttributes(stumpHDF_file, 'Drape', units='m', description='Planned Height')
qc.updateChannelAttributes(stumpHDF_file, 'eastvelocity', units='m/s')
qc.updateChannelAttributes(stumpHDF_file, 'heading', units='radian')
qc.updateChannelAttributes(stumpHDF_file, 'lat', units='degree')
qc.updateChannelAttributes(stumpHDF_file, 'lon', units='degree')
qc.updateChannelAttributes(stumpHDF_file, 'northvelocity', units='m/s')
qc.updateChannelAttributes(stumpHDF_file, 'pitch', units='radian')
qc.updateChannelAttributes(stumpHDF_file, 'roll', units='radian')
qc.updateChannelAttributes(stumpHDF_file, 'runnumber', description='Flight number')
qc.updateChannelAttributes(stumpHDF_file, 'Terrain', units='m')
qc.updateChannelAttributes(stumpHDF_file, 'time', units='s')
qc.updateChannelAttributes(stumpHDF_file, 'YYMMDD')
qc.updateChannelAttributes(stumpHDF_file, 'X_gda94', units='metre')
qc.updateChannelAttributes(stumpHDF_file, 'Y_gda94', units='metre')
qc.updateChannelAttributes(stumpHDF_file, 'X_wgs84', units='metre')
qc.updateChannelAttributes(stumpHDF_file, 'Y_wgs84', units='metre')
qc.updateChannelAttributes(stumpHDF_file, 'FAraw_Txx', units='eotvos')
qc.updateChannelAttributes(stumpHDF_file, 'FAraw_Txy', units='eotvos')
qc.updateChannelAttributes(stumpHDF_file, 'FAraw_Txz', units='eotvos')
qc.updateChannelAttributes(stumpHDF_file, 'FAraw_Tyy', units='eotvos')
qc.updateChannelAttributes(stumpHDF_file, 'FAraw_Tyz', units='eotvos')
qc.updateChannelAttributes(stumpHDF_file, 'FAraw_Tzz', units='eotvos')

In [ ]:
qc.reportWhizz(stumpHDF_file)

In [ ]:
qc.reportFlights(stumpHDF_file, flightChannel='runnumber', detailed=True)

In [ ]:
qc.reportSampling(stumpHDF_file)

In [ ]:
wp.linesMap([stumpHDF_file])

## Reports and formats
<div class="alert alert-block alert-warning">
RECTIFY
<div>

> All of the checks in this section are performed independently of the AirGravQC software and this notebook. But it is convenient to keep all the QC reporting in this one document.

> The acquirer is generally expected to deliver certain reports and data throughout the survey. The data are exxpected in certain formats. This section provides for reporting whether or not these requirements were met.

> Currently this example does not contain any reports. If it did, we would do the following checks.

#### Point located data format
<div class="alert alert-block alert-info">
ACCEPT
<div>

*Delivered point located field data shall be in ASEG-GDF2 format.*

Actually delivered in Geosoft XYZ. For field data this is not a problem so, even though this does not meet contractual requirements, it is acceptable. Channel descriptions file matches actual supplied channels as required.

#### Gridded data format
<div class="alert alert-block alert-info">
NA   
<div>

*The Deed specifies the gridded field data to be supplied. For the Canobie contract, none were required.*

> The Deed specifies ERMapper format.

No grids required and none supplied. Not applicable.

#### Static data to be supplied
<div class="alert alert-block alert-success">
PASS
<div>

*Gravity and navigation processed static readings must be reported to the Customer within 24 hours of every completed flight.*

Quiescent data has been supplied as required. This has been QC'd on a daily basis and no problems, concerns or failings were observed. All data has passed.

#### Field data to be supplied
<div class="alert alert-block alert-success">
PASS
<div>

*The Deed specifies the required channels for field delivery.*

Line data - all required channels delivered.

Channel description text file supplied.

#### Delivered reports
<div class="alert alert-block alert-warning">
TO RECTIFY
<div>

*The Deed requires a Commencement Report before acquisition commences, daily and weekly report through the project, and a final report at the end.*

Commencement report was received in timely manner and was checked against contract. All requirements met.

Daily reports have been received and have provided the information required under the contract.

Weekly reports - none received, supplier has been asked to rectify (email 30 Feb 2019).

Final report - only due at end of project.

#### Coordinates and Units
<div class="alert alert-block alert-info">
ACCEPT
<div>

*As per contract: Correct Coordinate Frame; correct Position Datum, Projected Coordinates and Height Datum; correct units.*

Checked manually.

Coord Frame - PASS

Position Datum - WGS84 incorrect but acceptable for field data.

Projected Coordinate - UTM 54 incorrect (should be MGA 54) but acceptable for field data.

Height Datum - EGM96 geoid incorrect but acceptable for field data.

Units - all correct except gravity which is in mGal instead of µm s<sup>-2</sup>. Accept since field data.

> I accept WGS84/UTM and I accept mGal for field data even though the Deed specifies GDA2020 / MGA and um/s/s. Enforcing the contract makes extra work for the acquirer on every delivery for usually no advantage.

## Navigation and positioning
<div class="alert alert-block alert-info">
ACCEPT
<div>

#### GNSS
<div class="alert alert-block alert-success">
PASS
<div>

*The Deed requires a minimum of 5 GNSS satellites visible for AGG acquisition, and PDOP, HDOP and VDOP to not exceed 4.*

All ok.

In [ ]:
qc.checkGNSS(canobieHDF_file, 'NumSats', 'PDOP', 'VDOP', 'HDOP', nsats_min=5, max_pdop=4, 
                  max_hdop=4, max_vdop=4)

> The above exemplifies my preferred reporting structure, with the contractual specification first, then any commentary or summary of QC, and finally, the actual QC check performed with its output. (`checkGNSS()` is the first instance in this notebook with all elements of the structure present.)

> Now, just to see what happens, we increase the required number of satellites to 9. The result is an error report on the one line that failed this more difficult requirement.

In [ ]:
qc.checkGNSS(canobieHDF_file, 'NumSats', 'PDOP', 'VDOP', 'HDOP', nsats_min=9, max_pdop=4, 
                  max_hdop=4, max_vdop=4)

#### Horizontal Position
<div class="alert alert-block alert-success">
PASS
<div>

*The Deed requires the horizontal position to not depart from the planned position by more than 40 m for more than 1000 m.*

All ok.

In [ ]:
qc.checkXYPlan(canobieHDF_plan, canobieHDF_file, allowance=40.0, maxCounter=0,
               maxDistance=1000.0, plot_flag=False)

> Just tightened up the requirement so we can see the report from `checkXYPlan()`.

In [ ]:
qc.checkXYPlan(canobieHDF_plan, canobieHDF_file, allowance=21.0, maxCounter=0,
               maxDistance=1000.0, plot_flag=True)

#### Vertical Position
<div class="alert alert-block alert-info">
NA
<div>

*The Deed requires the vertical position to not depart from the planned position by more than 20 m for more than 1000 m.*

> I can't find the planned drape for Canobie, but it proceeds very like the horizontal one. Just so you can see what this QC check does, we will run it on the EastVic project data.

In [ ]:
qc.checkVertPlan(EastVicHDF_plan, EastVicHDF_file, allowance=20.0, maxCounter=0,
                 maxDistance=1000.0, plot_flag=True)

#### Cross-over Heights
<div class="alert alert-block alert-info">
NA
<div>

*The Deed requires that the difference in height between traverse and control lines is less than some agreed maximum value.*

There are no control lines at Canobie and no specification so NA.

#### Segment Lengths
<div class="alert alert-block alert-success">
PASS
<div>

*The Deed requires a minimum line segment length. For Canobie, it was 11.2 km.*

OK

In [ ]:
qc.checkLineLengths(canobieHDF_file, min_len=11.2)

#### Line Overlaps
<div class="alert alert-block alert-success">
PASS
<div>

*The minimum overlap between segments of a line should be 600 m for AGG.*

> The report could be more informative here - "all overlaps met the requirement", say

In [ ]:
qc.checkOverlaps(canobieHDF_file, min_overlap=0.6, plot_flag=False)

#### Ground Clearance
<div class="alert alert-block alert-success">
PASS
<div>

*This is a non-contractual check that the aircraft did not approach the ground too closely; it is a simple safety check. The settings check if the aircraft came closer than 60 m from the ground. You can change this to a number of your choice.*

All ok. Also checked at 67 m just to get a plot!

In [ ]:
qc.checkSafeClearance(canobieHDF_file, 60.0, altitude_chan='HEIGHT', terrain_chan='DTM')

In [ ]:
qc.checkSafeClearance(canobieHDF_file, 67.0, altitude_chan='HEIGHT', terrain_chan='DTM')

#### Ground Speed
<div class="alert alert-block alert-success">
PASS
<div>

*The contract requires the ground speed to not exceed the range +/-15% of 60 m/s for more than 1000 m.*

All the data met the specification.

In [ ]:
qc.checkSpeeds(canobieHDF_file, nominalSpeed=60., allowance=0.15, maxDistance=1000.0, plot_flag=False)

> Tightening the specification to +/- 6% induces failures so we can see how AirGravQC reports them.

In [ ]:
qc.checkSpeeds(canobieHDF_file, nominalSpeed=60., allowance=0.06, maxDistance=1000.0, plot_flag=True)

## Gravimeter
<div class="alert alert-block alert-success">
PASS
<div>

> Canobie was a gradiometer project, so for this section we use the EastVic project data - EastVic was a gravimeter project.

#### Repeat lines
<div class="alert alert-block alert-success">
PASS
<div>

*Contract (p33): "the standard deviation of differences between terrain-corrected vertical gravity values along each repeat line pass and corresponding values from mean of all passes" ... "<= 12.5 µm/s/s for any individual pass" and "<= 7 µm/s/s for all passes combined."*

All repeat lines pass with the worst repeatability being 11.1 µm s<sup>-2</sup>.

Repeatability of vertical position was excellent, with RMS differences around 4 m for all lines.

In [ ]:
all_lines = ['7001.16', '7001.17', '7001.18', '7001.19', '7001.2', '7001.21',
             '7001.22', '7001.23', '7001.24', '7001.25']

In [ ]:
qc.checkRepeatLines(EastVicRepHDF_file, 'B100s-267_GEOID', all_lines, xOffset=False)

#### Test lines
<div class="alert alert-block alert-success">
PASS
<div>

First check repeatability - which is very good.

In [ ]:
all_lines = ['8001.04', '8001.05', '8001.06', '8001.07']

In [ ]:
qc.checkRepeatLines(EastVicTestHDF_file, 'B100s-267_GEOID', all_lines, xOffset=False)

Next, compare with ground gravity grid sampled onto a flight line. I downloaded the ground gravity grid from GADDS.

In [ ]:
grid_path = Path(data_root + r'Gravmap2019-grid-grv_cscba-IncludesAirborne.ers')

In [ ]:
qc.diffGroundGrid(EastVicTestHDF_file, 'B100s-267_GEOID', '8001.04', grid_path, plot_title='Ground & Airborne Comparison')

The data look very similar but the differences are up to ~ 10 µm s<sup>-2</sup> or more. Let's see how good the ground gravity are.

In [ ]:
wp.plotLinesOnGroundStns(EastVicTestHDF_file, '8001.04', minlon=145.65, maxlon=146.15,
                         minlat=-36.45, maxlat=-36.15, min_reliability=0, fig_title='')

The ground gravity information is downloaded live from GA. The accuracy, reliability and height error information seem to be missing here but we can see the station locations. The data are relatively sparse so some of the difference is likely due to interpolation error from gridding the ground gravity. Some may be due to error in the airborne data.

#### Line Intersections
<div class="alert alert-block alert-success">
PASS
<div>

> TBD

#### Static data
<div class="alert alert-block alert-success">
PASS
<div>

*The specification says ...*

Static gravimeter data pre- and post-flight were supplied each day of flying as required and all met the specification.

#### Atmospheric corrections
<div class="alert alert-block alert-success">
PASS
<div>

In [ ]:
qc.checkAtmosEffect(EastVicHDF_file, 'ATMCOR', GRS80_height='MGA_Z')

#### Free-air corrections
<div class="alert alert-block alert-success">
PASS
<div>

In [ ]:
qc.checkFreeAirCorr(EastVicHDF_file, 'FACOR_GRS80')

#### Eotvos corrections
<div class="alert alert-block alert-success">
PASS
<div>

In [ ]:
qc.checkEotvosCorr(EastVicHDF_file, 'EOTCOR', east_vel='V_EAST', north_vel='V_NORTH')

#### Latitude corrections
<div class="alert alert-block alert-success">
PASS
<div>

In [ ]:
qc.checkLatCorr(EastVicHDF_file, 'LATCOR')

#### Aircraft Accelerations
<div class="alert alert-block alert-success">
PASS
<div>

In [ ]:
qc.allChanStats(EastVicHDF_file,allChannels=['FX', 'FY', 'FZ'])

## AGG Gradiometer
<div class="alert alert-block alert-success">
PASS
<div>

#### Quiescent Noise
<div class="alert alert-block alert-success">
PASS
<div>

*Deed requires quiescent data collected before each flight and the results delivered in the the daily report. Average signal power density over both complements is required to be below $10E^{2}/rad/sec$.*

Quiescent data were supplied daily by email as required and were checked on arrival. All quiescent data was below 10 E^2/r/s as required.

#### AGG Noise
<div class="alert alert-block alert-success">
PASS
<div>

*Deed requires that any line with an average noise above 5.0 E be re-flown.*

OK

> The noise depends on turbulence so it is instructive to plot each noise channel against turbulence. This also shows any outliers from the general trend (There are too few lines to see a trend here.)

> Although the specification is 5.0 E, let's set it to 2.5 E so that we get a line to fail. If we set labelLines=True, then all failed lines are labeled on the plot.

In [ ]:
qc.diffNoiseVturb(canobieHDF_file, eNE='Noise_NE', eUV='Noise_UV', turbulence='TURBULENCE',
                  error_spec=2.5, labelLines=True)

> Any rectification process can down-convert high frequency vibration into the signal band of a sensor. Gravity gradiometers have an intrinsic rectification process via their sensitivity to products of rotational velocity so it is useful to check for excess high frequency signal since it may lead to error in the final data.

> For the AGG system, a noiseLimit of ~15 E ought to be followed up with the acquisition company. Here I set the noiseLimit much lower in order to demonstrate the plotting of the result.

> The raw gradients are high-pass filtered and a rolling standard deviation is used to find periods of higher amplitudes. Turbulence is a likely cause of excess vibration so the turbulence is also plotted for comparison.

> This is not a contractual check in the Deed.

In [ ]:
qc.checkRawAGG(canobieHDF_file, 'ANE_TC_2p67', 'AUV_TC_2p67', 'BNE_TC_2p67', 'BUV_TC_2p67', 'TURBULENCE', noiseLimit=6.5)

## FTG Gradiometer
<div class="alert alert-block alert-info">
ACCEPT
<div>

> `AirGravQC` includes functions for the QC of FTG data but we do not have field data available to test it on. Instead we will "fake it to make it".

FTG data in the field is delivered with the raw in-line and cross gradients and it is these channels that the following QC functions check. The final data does not include the in-line and cross data and all delivered gradients have been filtered and transformed to components of the tensor representation. The transformation exploits Laplace's equation which means that the ensor trace is, by construction, zero. This makes all the tests against the trace useless.

So these examples would be much more realistic with the raw in-line and cross gradients. Nevertheless, some can be run with the supplied final components and this is done here to demonstrate the use of the functions. The results are, however, meaningless.

> `ilsNoiseVturb()` performs the same task as `diffNoiseVturb()` does for AGG but it uses the in-line sum as the measure of noise instead of the difference noise.

Here we get very low noise estimates because we are inputting (despite the channel names) final transformed data.

In [ ]:
qc.ilsNoiseVturb(stumpHDF_file, 'FAraw_Txx', 'FAraw_Tyy', 'FAraw_Tzz', vertdispl='altitude')

> `checkRawFTG()` performs the same task as `checkRawAGG()` but using the raw FTG in-line and cross channels.

The aim is to check for periods of excess high frequency noise. The usual `noiseLimit` is 50 but the final data used as input to the function have been heavily filtered and so it has been set to 30 here just to get some plots.

In [ ]:
qc.checkRawFTG(stumpHDF_file, lines=[], gradients=['FAraw_Txx', 'FAraw_Tyy', 'FAraw_Tzz'], noiseLimit=30, vertdispl='altitude')

> `checkInlineSum()` calculates the in-line sum from the raw FTG in-line channels, plotting and reporting results.

The inputs are transformed gradients and so are constructed using Laplace's equation. Consequently the in-line sum is, by construction, zero and so this is not a true test. It does work if applied to the in-line components delivered in field data.

The non-zero values are due to the conversion of the data into text in the `XYZ` files.

In [ ]:
qc.checkInlineSum(stumpHDF_file, inline1='FAraw_Txx', inline2='FAraw_Tyy', inline3='FAraw_Tzz', dontfilter=True)

> `eigenPlot()` checks the Frobenius norm of the tensor and plots results if it exceeds the noise limit.

It relies on having the raw inline and cross gradients which we do not have in the Blackstump data-set and their is no sensible way to fake it here.

In [ ]:
# qc.eigenPlot(stumpHDF_file, lines = [], noiselimit=30.0)

## Statistics and Grids
<div class="alert alert-block alert-info">
NA
<div>

#### Data Quality
<div class="alert alert-block alert-success">
PASS
<div>

*None of the following checks are contractually required but they can give some insights to data quality.*

---
The only spikes found were at very small amplitudes on otherwise smooth fields (terrain corrections). All ok.

> The following channels should vary smoothly without spikes. You can choose different channels to test for your project but I have found this test to generally be too sensitive. The algorithm could be improved.

In [ ]:
qc.checkSpikes(canobieHDF_file, fields=['Bearing', 'Noise_NE', 'Noise_UV', 'gD_Fourier_2p67', 'T_DD', 'T_NE', 'T_UV', \
                            'LATITUDE', 'LONGITUDE', 'EASTING', 'NORTHING', 'DTM'])

---
The only failures are in the `Time_Day` channel and all are within 1 second of midnight. Time of day does not vary with constant slope at midnight so this is not a concern. Of course the aircraft was not flying at midnight, suggesting the the relevant clock is in the wrong time zone but this is not a concern.

> The checked fields should each vary uniformly with constant slope.

In [ ]:
qc.checkConstantSlope(canobieHDF_file, fields=['Date', 'FIDUCIAL', 'FLIGHT', 'LINE', 'Time_Day', 'JOB_ID', \
                                   'Time_1980'])

---
All channel statistics look as expected. OK.

> Just plot the mean, standard deviation and range of every channel as a for every line. A lot of information condensed here which I find useful. I just run my eye quickly over the plots looking for outliers, and I check the vertical scales to ensure that the values are in about the right range.

In [ ]:
# Normally, plot the stats for all channels whatsoever. But to save space, we will just do a few in the next notebook cell, and comment this one out.
# qc.allChanStats(canobieHDF_file, ['ANE_TC_2p67', 'AUV_TC_2p67', 'BNE_TC_2p67', 'BUV_TC_2p67', 'Bearing',
#                      'CLEARANCE', 'DTM', 'Date', 'EASTING', 'FIDUCIAL', 'FLIGHT', 'GDD_Fourier_2p67',
#                      'GNE_Fourier_2p67', 'GUV_Fourier_2p67', 'HDOP', 'HEIGHT', 'JOB_ID', 'LATITUDE',
#                      'LINE', 'LONGITUDE', 'NORTHING', 'Noise_NE', 'Noise_UV', 'NumSats', 'PDOP',
#                      'TURBULENCE', 'T_DD', 'T_NE', 'T_UV', 'Time_1980', 'Time_Day', 'VDOP', 'gD_Fourier_2p67'])

In [ ]:
qc.allChanStats(canobieHDF_file, ['CLEARANCE', 'DTM', 'HEIGHT', 'Noise_NE', 'Noise_UV', 'NumSats', 'PDOP',
                     'TURBULENCE', 'T_DD', 'T_NE', 'T_UV', 'gD_Fourier_2p67'])

In [ ]:
qc.allChanStats(canobieHDF_file, ['CLEARANCE', 'DTM'])

#### Even-Odd Grids
<div class="alert alert-block alert-info">
NA
<div>

> Currently, `AirGravQC` does not have a capacity to separately grid odd and even lines, then analyse the difference between the grids.

#### Delivered Grids
<div class="alert alert-block alert-info">
NA
<div>

*For Canobie, there was no requirement for grids of field data to be delivered and none were.*

> The Deed does not have specifications on the quality of gridded field data but grids are a quick and easy way to spot any artefacts in the data. So they are useful in checking for "best practice".

> The function `checkErsHeaders()` is useful when there are supplied grids.

> In any case, I always generate grids from the located data.

In [ ]:
# qc.checkErsHeaders(ersp)

#### Generated Grids
<div class="alert alert-block alert-success">
PASS
<div>

*There are no Deed specifications on the grids except "best practice".*

All the grids look okay and there are no serious artefacts.

> I grid and image almost every channel in the database (here I have only done a few as examples). Channels that are directionally dependent have the mean for each line removed ("mr") before gridding. For some channels it is more useful to examine the grid of the first difference along each line ("d1").

> It might be useful to comment on some particular images.

In [ ]:
z_chans = ['Bearing', 'CLEARANCE', 'DTM', 'FLIGHT', 'GDD_Fourier_2p67', 'NumSats',
           'T_DD', 'Time_1980', 'gD_Fourier_2p67']
mr_chans = ['Bearing']
d1_chans = ['FLIGHT', 'Time_1980']
qc.grid_n_image(canobieHDF_file, z_chans, mr_chans, d1_chans, 500.0)